[package]
name = "codable"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
indexmap = { version = "1.9.1", optional = true }
thiserror = "1.0.34"
tracing = { version = "0.1.37", optional = true }
